### PR TITLE
feat(command): Pass command from experiment spec to runner

### LINKED ISSUE #152: Support custom commands in runner images
## FEATURE REQUEST

Containers commands are currently hardcoded to `/bin/bash`. See [pkg/utils/builders.go#L26](https://github.com/litmuschaos/chaos-runner/blob/master/pkg/utils/builders.go#L26).

We want to use a custom runner image (without bash).

### PR DESCRIPTION
**Pull request by jnodorp-jaconi**
Closes #152

### CODE REVIEW

**Comment by ksatchit** [comment]
Thanks for this PR @jnodorp-jaconi ! Just curious - are you building out your own version of the experiment image?

**Review by ksatchit — DISMISSED** [review]
lgtm

**Review by uditgaurav — DISMISSED** [review]

**Comment by jnodorp-jaconi** [comment]
> Just curious - are you building out your own version of the experiment image?

Yes, exactly. I am currently chaos testing an application that uses GCP ([Google Dataproc](https://cloud.google.com/dataproc) to be specific), so I built a custom image providing GCP specific experiments (shutdown VM instance, reboot VM instance, ...).

**Comment by jnodorp-jaconi** [comment]
Rebased...

**Review by uditgaurav — APPROVED** [review]

**Review by ispeakc0de — APPROVED** [review]

**Pull request merged**
