### PR TITLE
(chore) Changed DefaultMode of Job Deletion as Always

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>

**What this PR does / why we need it**:

- Ensures the default jobCleanupPolicy is set to "delete"

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has document related information
- [ ] Labelled this PR & related issue with `breaking-changes` tag
- [ ] PR messages has breaking changes related information
- [ ] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] PR messages has upgrade related information
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by rahulchheda** [comment]
Can we add ENV here @ispeakc0de https://github.com/litmuschaos/chaos-runner/blob/9599175389f733bb7d35b22e8c021658f0c08a9c/pkg/utils/experimentHelpers.go#L40 ?

**Comment by ksatchit** [comment]
@rahulchheda , do you think this change is better done at the operator side?

**Comment by chandankumar4** [comment]
> @rahulchheda , do you think this change is better done at the operator side?

I think if a runner is spawning an experiment pod then better to delete it by runner

**Comment by rahulchheda** [comment]
> > @rahulchheda , do you think this change is better done at the operator side?
> 
> I think if a runner is spawning an experiment pod then better to delete it by runner

@ksatchit was talking about setting the defaults in chaos engine , like the jobCleanUpPolicy, runner images, and other defaults from operator, and then keep the functionality of the runner as it is.

**Comment by ksatchit** [comment]
> > @rahulchheda , do you think this change is better done at the operator side?
> 
> I think if a runner is spawning an experiment pod then better to delete it by runner

The comment is not related to who is deleting, the runner is the one deleting the experiment pod right from the beginning. It was an alternate possibility about the place where we set defaults to items read from spec. There is  a set of engine attributes whose defaults are being placed in the operator - annotationCheck for instance. Likewise for app info. On the same lines, in principle, should the jobCleanupPolicy be initialized there and passed down to runner was the question. However, since the job lifecycle management is essentially a runner activity, it would still be OK to do it here. IMO, the engineSpec has to be enhanced to separate out which set of items in the engine spec are to be interpreted by the operator v/s runner. This can be ironed out in subsequent releases.

**Pull request merged**
